#!/bin/bash

#Configuration variables for FTS3 testing scripts

export FTS3_HOST=${TARGET_HOST-"`hostname -f`"}
export FTS3_PORT=${FTS3_PORT-8443}
export FTS3_REST_PORT=${FTS3_REST_PORT-8446}
export BDII_HOST=${BDII_HOST-"lcg-bdii.cern.ch"}
export LCG_GFAL_INFOSYS=${LCG_GFAL_INFOSYS-"$BDII_HOST:2170"}

rpm -qa | grep fts

#export DEBUG=1

voms-proxy-info --all


