#!/bin/sh
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2010
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# Based on Alejandro Álvarez Ayllón script CERN
# 
#
##############################################################################

#
# Exits with a success
function TEST_PASSED {
  echo "-TEST PASSED-"
  exit 0
}
# Exits with a warning
function TEST_WARN {
  if [ $# -ge 1 ]; then
    echo $1
  fi
  echo "-TEST WARN-"
  exit 250
}
# Exits with a failure
# @param $1 The message
# @param $2 The exit code (optional)
function TEST_FAILED {
  if [ $# -ge 1 ]; then
    echo $1
  fi
  echo "-TEST FAILED-"
 exit 1
}
