DROP INDEX site_group_sname_id     ON t_site_group;
DROP INDEX job_job_state           ON t_job;
DROP INDEX job_vo_name             ON t_job;
DROP INDEX job_cred_id             ON t_job;
DROP INDEX job_jobfinished_id      ON t_job;
DROP INDEX job_job_A               ON t_job;
DROP INDEX job_priority            ON t_job;
DROP INDEX job_submit_time         ON t_job;
DROP INDEX file_job_id             ON t_file;
DROP INDEX file_file_state_job_id  ON t_file;
DROP INDEX file_jobfinished_id     ON t_file;
DROP INDEX file_job_id_a           ON t_file;
DROP INDEX file_finish_time        ON t_file;
DROP INDEX optimize_source_a       ON t_optimize;
DROP INDEX optimize_dest_se        ON t_optimize;
DROP INDEX optimize_nostreams      ON t_optimize;
DROP INDEX optimize_timeout        ON t_optimize;
DROP INDEX optimize_buffer         ON t_optimize;
DROP INDEX idx_report_job          ON t_job;
DROP INDEX stagereq_request_id     ON t_stage_req;
DROP INDEX stagereq_file_id        ON t_stage_req;
DROP INDEX stagereq_job_id         ON t_stage_req;
DROP INDEX stagereq_stage_state    ON t_stage_req;
DROP INDEX stagereq_jobfinished_id ON t_stage_req;
DROP INDEX t_group_members_1       ON t_group_members;
DROP INDEX t_group_members_2       ON t_group_members;

DROP TABLE t_job_backup;
DROP TABLE t_file_backup;
DROP TABLE t_schema_vers;
DROP TABLE t_stage_req;
DROP TABLE t_file;
DROP TABLE t_job_share_config;
DROP TABLE t_job;
DROP TABLE t_vo_acl;
DROP TABLE t_se_pair_acl;
DROP TABLE t_site_group;
DROP TABLE t_bad_dns;
DROP TABLE t_bad_ses;
DROP TABLE t_share_config;
DROP TABLE t_link_config;
DROP TABLE t_group_members;
DROP TABLE t_se_acl;
DROP TABLE t_se;
DROP TABLE t_credential_vers;
DROP TABLE t_credential;
DROP TABLE t_credential_cache;
DROP TABLE t_debug;
DROP TABLE t_config_audit;
DROP TABLE t_optimize;
DROP TABLE t_log;
DROP TABLE t_server_config;
