#
# Copyright (c) CERN 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM centos:7

# Required repos
ADD "http://dmc-repo.web.cern.ch/dmc-repo/dmc-ci-el7.repo" "/etc/yum.repos.d/"
ADD "http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" "/etc/yum.repos.d/"

RUN yum install -y epel-release yum-utils

# Build requirements
RUN yum install -y gcc gcc-c++
RUN yum-builddep -y fts-server

# Run dependencies
RUN yum install -y gfal2-plugin-mock \
    lcg-CA supervisor voms-config-vo-dteam

# Build fts3 with coverage
COPY . /usr/src/fts3
WORKDIR /usr/src/fts3
RUN CFLAGS=--coverage CXXFLAGS=--coverage cmake . \
        -DMAINBUILD=ON -DSERVERBUILD=ON -DCLIENTBUILD=ON -DMYSQLBUILD=ON \
        -DTESTBUILD=ON -DCMAKE_INSTALL_PREFIX=""
RUN make -j2
RUN make install

# Configure supervisord
ADD "qa/supervisord.conf" "/etc/supervisord.conf"

# Volumes
VOLUME ["/etc/fts3", "/logs", "/coverage"]

# Run supervisor when the container starts
ENTRYPOINT ["/usr/bin/supervisord", "--configuration", "/etc/supervisord.conf"]
