/* fts3Server.cpp
   Generated by gSOAP 2.7.16 from /home/simonm/tmp/build/src/ws-ifce/gsoap/gsoap_interface.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "fts3H.h"

namespace fts3 {

SOAP_SOURCE_STAMP("@(#) fts3Server.cpp ver 2.7.16 2013-02-05 11:10:01 GMT")


SOAP_FMAC5 int SOAP_FMAC6 fts3_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || fts3_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 fts3_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getVersion"))
		return soap_serve_delegation__getVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getInterfaceVersion"))
		return soap_serve_delegation__getInterfaceVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getServiceMetadata"))
		return soap_serve_delegation__getServiceMetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getProxyReq"))
		return soap_serve_delegation__getProxyReq(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getNewProxyReq"))
		return soap_serve_delegation__getNewProxyReq(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:renewProxyReq"))
		return soap_serve_delegation__renewProxyReq(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:putProxy"))
		return soap_serve_delegation__putProxy(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:getTerminationTime"))
		return soap_serve_delegation__getTerminationTime(soap);
	if (!soap_match_tag(soap, soap->tag, "delegation:destroy"))
		return soap_serve_delegation__destroy(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:setConfiguration"))
		return soap_serve_implcfg__setConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:delConfiguration"))
		return soap_serve_implcfg__delConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:getConfiguration"))
		return soap_serve_implcfg__getConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:doDrain"))
		return soap_serve_implcfg__doDrain(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:setRetry"))
		return soap_serve_implcfg__setRetry(soap);
	if (!soap_match_tag(soap, soap->tag, "implcfg:setQueueTimeout"))
		return soap_serve_implcfg__setQueueTimeout(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:transferSubmit"))
		return soap_serve_impltns__transferSubmit(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:transferSubmit2"))
		return soap_serve_impltns__transferSubmit2(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:transferSubmit3"))
		return soap_serve_impltns__transferSubmit3(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:transferSubmit4"))
		return soap_serve_impltns__transferSubmit4(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:prioritySet"))
		return soap_serve_impltns__prioritySet(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:debugSet"))
		return soap_serve_impltns__debugSet(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:blacklist"))
		return soap_serve_impltns__blacklist(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:listRequests"))
		return soap_serve_impltns__listRequests(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:listRequests2"))
		return soap_serve_impltns__listRequests2(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getFileStatus"))
		return soap_serve_impltns__getFileStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getFileStatus2"))
		return soap_serve_impltns__getFileStatus2(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getTransferJobStatus"))
		return soap_serve_impltns__getTransferJobStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getTransferJobSummary"))
		return soap_serve_impltns__getTransferJobSummary(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getTransferJobSummary2"))
		return soap_serve_impltns__getTransferJobSummary2(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:cancel"))
		return soap_serve_impltns__cancel(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:setJobPriority"))
		return soap_serve_impltns__setJobPriority(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:addVOManager"))
		return soap_serve_impltns__addVOManager(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:removeVOManager"))
		return soap_serve_impltns__removeVOManager(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:listVOManagers"))
		return soap_serve_impltns__listVOManagers(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getRoles"))
		return soap_serve_impltns__getRoles(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getRolesOf"))
		return soap_serve_impltns__getRolesOf(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getVersion"))
		return soap_serve_impltns__getVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getSchemaVersion"))
		return soap_serve_impltns__getSchemaVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getInterfaceVersion"))
		return soap_serve_impltns__getInterfaceVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "impltns:getServiceMetadata"))
		return soap_serve_impltns__getServiceMetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "log:GetLog"))
		return soap_serve_log__GetLog(soap);
	if (!soap_match_tag(soap, soap->tag, "log:GetLogInternal"))
		return soap_serve_log__GetLogInternal(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getVersion(struct soap *soap)
{	struct delegation__getVersion soap_tmp_delegation__getVersion;
	struct delegation__getVersionResponse _param_1;
	soap_default_delegation__getVersionResponse(soap, &_param_1);
	soap_default_delegation__getVersion(soap, &soap_tmp_delegation__getVersion);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getVersion(soap, &soap_tmp_delegation__getVersion, "delegation:getVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getVersion(soap, _param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getVersionResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getVersionResponse(soap, &_param_1, "delegation:getVersionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getVersionResponse(soap, &_param_1, "delegation:getVersionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getInterfaceVersion(struct soap *soap)
{	struct delegation__getInterfaceVersion soap_tmp_delegation__getInterfaceVersion;
	struct delegation__getInterfaceVersionResponse _param_2;
	soap_default_delegation__getInterfaceVersionResponse(soap, &_param_2);
	soap_default_delegation__getInterfaceVersion(soap, &soap_tmp_delegation__getInterfaceVersion);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getInterfaceVersion(soap, &soap_tmp_delegation__getInterfaceVersion, "delegation:getInterfaceVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getInterfaceVersion(soap, _param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getInterfaceVersionResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getInterfaceVersionResponse(soap, &_param_2, "delegation:getInterfaceVersionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getInterfaceVersionResponse(soap, &_param_2, "delegation:getInterfaceVersionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getServiceMetadata(struct soap *soap)
{	struct delegation__getServiceMetadata soap_tmp_delegation__getServiceMetadata;
	struct delegation__getServiceMetadataResponse _param_3;
	soap_default_delegation__getServiceMetadataResponse(soap, &_param_3);
	soap_default_delegation__getServiceMetadata(soap, &soap_tmp_delegation__getServiceMetadata);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getServiceMetadata(soap, &soap_tmp_delegation__getServiceMetadata, "delegation:getServiceMetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getServiceMetadata(soap, soap_tmp_delegation__getServiceMetadata._key, _param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getServiceMetadataResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getServiceMetadataResponse(soap, &_param_3, "delegation:getServiceMetadataResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getServiceMetadataResponse(soap, &_param_3, "delegation:getServiceMetadataResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getProxyReq(struct soap *soap)
{	struct delegation__getProxyReq soap_tmp_delegation__getProxyReq;
	struct delegation__getProxyReqResponse _param_4;
	soap_default_delegation__getProxyReqResponse(soap, &_param_4);
	soap_default_delegation__getProxyReq(soap, &soap_tmp_delegation__getProxyReq);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getProxyReq(soap, &soap_tmp_delegation__getProxyReq, "delegation:getProxyReq", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getProxyReq(soap, soap_tmp_delegation__getProxyReq._delegationID, _param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getProxyReqResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getProxyReqResponse(soap, &_param_4, "delegation:getProxyReqResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getProxyReqResponse(soap, &_param_4, "delegation:getProxyReqResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getNewProxyReq(struct soap *soap)
{	struct delegation__getNewProxyReq soap_tmp_delegation__getNewProxyReq;
	struct delegation__getNewProxyReqResponse _param_5;
	soap_default_delegation__getNewProxyReqResponse(soap, &_param_5);
	soap_default_delegation__getNewProxyReq(soap, &soap_tmp_delegation__getNewProxyReq);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getNewProxyReq(soap, &soap_tmp_delegation__getNewProxyReq, "delegation:getNewProxyReq", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getNewProxyReq(soap, _param_5);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getNewProxyReqResponse(soap, &_param_5);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getNewProxyReqResponse(soap, &_param_5, "delegation:getNewProxyReqResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getNewProxyReqResponse(soap, &_param_5, "delegation:getNewProxyReqResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__renewProxyReq(struct soap *soap)
{	struct delegation__renewProxyReq soap_tmp_delegation__renewProxyReq;
	struct delegation__renewProxyReqResponse _param_6;
	soap_default_delegation__renewProxyReqResponse(soap, &_param_6);
	soap_default_delegation__renewProxyReq(soap, &soap_tmp_delegation__renewProxyReq);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__renewProxyReq(soap, &soap_tmp_delegation__renewProxyReq, "delegation:renewProxyReq", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__renewProxyReq(soap, soap_tmp_delegation__renewProxyReq._delegationID, _param_6);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__renewProxyReqResponse(soap, &_param_6);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__renewProxyReqResponse(soap, &_param_6, "delegation:renewProxyReqResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__renewProxyReqResponse(soap, &_param_6, "delegation:renewProxyReqResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__putProxy(struct soap *soap)
{	struct delegation__putProxy soap_tmp_delegation__putProxy;
	struct delegation__putProxyResponse _param_7;
	soap_default_delegation__putProxyResponse(soap, &_param_7);
	soap_default_delegation__putProxy(soap, &soap_tmp_delegation__putProxy);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__putProxy(soap, &soap_tmp_delegation__putProxy, "delegation:putProxy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__putProxy(soap, soap_tmp_delegation__putProxy._delegationID, soap_tmp_delegation__putProxy._proxy, _param_7);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__putProxyResponse(soap, &_param_7);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__putProxyResponse(soap, &_param_7, "delegation:putProxyResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__putProxyResponse(soap, &_param_7, "delegation:putProxyResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__getTerminationTime(struct soap *soap)
{	struct delegation__getTerminationTime soap_tmp_delegation__getTerminationTime;
	struct delegation__getTerminationTimeResponse _param_8;
	soap_default_delegation__getTerminationTimeResponse(soap, &_param_8);
	soap_default_delegation__getTerminationTime(soap, &soap_tmp_delegation__getTerminationTime);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__getTerminationTime(soap, &soap_tmp_delegation__getTerminationTime, "delegation:getTerminationTime", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__getTerminationTime(soap, soap_tmp_delegation__getTerminationTime._delegationID, _param_8);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__getTerminationTimeResponse(soap, &_param_8);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__getTerminationTimeResponse(soap, &_param_8, "delegation:getTerminationTimeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__getTerminationTimeResponse(soap, &_param_8, "delegation:getTerminationTimeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_delegation__destroy(struct soap *soap)
{	struct delegation__destroy soap_tmp_delegation__destroy;
	struct delegation__destroyResponse _param_9;
	soap_default_delegation__destroyResponse(soap, &_param_9);
	soap_default_delegation__destroy(soap, &soap_tmp_delegation__destroy);
	soap->encodingStyle = NULL;
	if (!soap_get_delegation__destroy(soap, &soap_tmp_delegation__destroy, "delegation:destroy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = delegation__destroy(soap, soap_tmp_delegation__destroy._delegationID, _param_9);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_delegation__destroyResponse(soap, &_param_9);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_delegation__destroyResponse(soap, &_param_9, "delegation:destroyResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_delegation__destroyResponse(soap, &_param_9, "delegation:destroyResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__setConfiguration(struct soap *soap)
{	struct implcfg__setConfiguration soap_tmp_implcfg__setConfiguration;
	struct implcfg__setConfigurationResponse _param_10;
	soap_default_implcfg__setConfigurationResponse(soap, &_param_10);
	soap_default_implcfg__setConfiguration(soap, &soap_tmp_implcfg__setConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__setConfiguration(soap, &soap_tmp_implcfg__setConfiguration, "implcfg:setConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__setConfiguration(soap, soap_tmp_implcfg__setConfiguration._configuration, _param_10);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__setConfigurationResponse(soap, &_param_10);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__setConfigurationResponse(soap, &_param_10, "implcfg:setConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__setConfigurationResponse(soap, &_param_10, "implcfg:setConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__delConfiguration(struct soap *soap)
{	struct implcfg__delConfiguration soap_tmp_implcfg__delConfiguration;
	struct implcfg__delConfigurationResponse _param_11;
	soap_default_implcfg__delConfigurationResponse(soap, &_param_11);
	soap_default_implcfg__delConfiguration(soap, &soap_tmp_implcfg__delConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__delConfiguration(soap, &soap_tmp_implcfg__delConfiguration, "implcfg:delConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__delConfiguration(soap, soap_tmp_implcfg__delConfiguration._configuration, _param_11);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__delConfigurationResponse(soap, &_param_11);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__delConfigurationResponse(soap, &_param_11, "implcfg:delConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__delConfigurationResponse(soap, &_param_11, "implcfg:delConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__getConfiguration(struct soap *soap)
{	struct implcfg__getConfiguration soap_tmp_implcfg__getConfiguration;
	struct implcfg__getConfigurationResponse _param_12;
	soap_default_implcfg__getConfigurationResponse(soap, &_param_12);
	soap_default_implcfg__getConfiguration(soap, &soap_tmp_implcfg__getConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__getConfiguration(soap, &soap_tmp_implcfg__getConfiguration, "implcfg:getConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__getConfiguration(soap, soap_tmp_implcfg__getConfiguration.vo, soap_tmp_implcfg__getConfiguration.name, soap_tmp_implcfg__getConfiguration.source, soap_tmp_implcfg__getConfiguration.destination, _param_12);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__getConfigurationResponse(soap, &_param_12);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__getConfigurationResponse(soap, &_param_12, "implcfg:getConfigurationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__getConfigurationResponse(soap, &_param_12, "implcfg:getConfigurationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__doDrain(struct soap *soap)
{	struct implcfg__doDrain soap_tmp_implcfg__doDrain;
	struct implcfg__doDrainResponse _param_13;
	soap_default_implcfg__doDrainResponse(soap, &_param_13);
	soap_default_implcfg__doDrain(soap, &soap_tmp_implcfg__doDrain);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__doDrain(soap, &soap_tmp_implcfg__doDrain, "implcfg:doDrain", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__doDrain(soap, soap_tmp_implcfg__doDrain.drain, _param_13);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__doDrainResponse(soap, &_param_13);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__doDrainResponse(soap, &_param_13, "implcfg:doDrainResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__doDrainResponse(soap, &_param_13, "implcfg:doDrainResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__setRetry(struct soap *soap)
{	struct implcfg__setRetry soap_tmp_implcfg__setRetry;
	struct implcfg__setRetryResponse _param_14;
	soap_default_implcfg__setRetryResponse(soap, &_param_14);
	soap_default_implcfg__setRetry(soap, &soap_tmp_implcfg__setRetry);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__setRetry(soap, &soap_tmp_implcfg__setRetry, "implcfg:setRetry", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__setRetry(soap, soap_tmp_implcfg__setRetry.retry, _param_14);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__setRetryResponse(soap, &_param_14);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__setRetryResponse(soap, &_param_14, "implcfg:setRetryResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__setRetryResponse(soap, &_param_14, "implcfg:setRetryResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_implcfg__setQueueTimeout(struct soap *soap)
{	struct implcfg__setQueueTimeout soap_tmp_implcfg__setQueueTimeout;
	struct implcfg__setQueueTimeoutResponse _param_15;
	soap_default_implcfg__setQueueTimeoutResponse(soap, &_param_15);
	soap_default_implcfg__setQueueTimeout(soap, &soap_tmp_implcfg__setQueueTimeout);
	soap->encodingStyle = NULL;
	if (!soap_get_implcfg__setQueueTimeout(soap, &soap_tmp_implcfg__setQueueTimeout, "implcfg:setQueueTimeout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = implcfg__setQueueTimeout(soap, soap_tmp_implcfg__setQueueTimeout.timeout, _param_15);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_implcfg__setQueueTimeoutResponse(soap, &_param_15);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_implcfg__setQueueTimeoutResponse(soap, &_param_15, "implcfg:setQueueTimeoutResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_implcfg__setQueueTimeoutResponse(soap, &_param_15, "implcfg:setQueueTimeoutResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__transferSubmit(struct soap *soap)
{	struct impltns__transferSubmit soap_tmp_impltns__transferSubmit;
	struct impltns__transferSubmitResponse _param_16;
	soap_default_impltns__transferSubmitResponse(soap, &_param_16);
	soap_default_impltns__transferSubmit(soap, &soap_tmp_impltns__transferSubmit);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__transferSubmit(soap, &soap_tmp_impltns__transferSubmit, "impltns:transferSubmit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__transferSubmit(soap, soap_tmp_impltns__transferSubmit._job, _param_16);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__transferSubmitResponse(soap, &_param_16);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__transferSubmitResponse(soap, &_param_16, "impltns:transferSubmitResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__transferSubmitResponse(soap, &_param_16, "impltns:transferSubmitResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__transferSubmit2(struct soap *soap)
{	struct impltns__transferSubmit2 soap_tmp_impltns__transferSubmit2;
	struct impltns__transferSubmit2Response _param_17;
	soap_default_impltns__transferSubmit2Response(soap, &_param_17);
	soap_default_impltns__transferSubmit2(soap, &soap_tmp_impltns__transferSubmit2);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__transferSubmit2(soap, &soap_tmp_impltns__transferSubmit2, "impltns:transferSubmit2", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__transferSubmit2(soap, soap_tmp_impltns__transferSubmit2._job, _param_17);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__transferSubmit2Response(soap, &_param_17);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__transferSubmit2Response(soap, &_param_17, "impltns:transferSubmit2Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__transferSubmit2Response(soap, &_param_17, "impltns:transferSubmit2Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__transferSubmit3(struct soap *soap)
{	struct impltns__transferSubmit3 soap_tmp_impltns__transferSubmit3;
	struct impltns__transferSubmit3Response _param_18;
	soap_default_impltns__transferSubmit3Response(soap, &_param_18);
	soap_default_impltns__transferSubmit3(soap, &soap_tmp_impltns__transferSubmit3);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__transferSubmit3(soap, &soap_tmp_impltns__transferSubmit3, "impltns:transferSubmit3", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__transferSubmit3(soap, soap_tmp_impltns__transferSubmit3._job, _param_18);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__transferSubmit3Response(soap, &_param_18);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__transferSubmit3Response(soap, &_param_18, "impltns:transferSubmit3Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__transferSubmit3Response(soap, &_param_18, "impltns:transferSubmit3Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__transferSubmit4(struct soap *soap)
{	struct impltns__transferSubmit4 soap_tmp_impltns__transferSubmit4;
	struct impltns__transferSubmit4Response _param_19;
	soap_default_impltns__transferSubmit4Response(soap, &_param_19);
	soap_default_impltns__transferSubmit4(soap, &soap_tmp_impltns__transferSubmit4);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__transferSubmit4(soap, &soap_tmp_impltns__transferSubmit4, "impltns:transferSubmit4", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__transferSubmit4(soap, soap_tmp_impltns__transferSubmit4._job, _param_19);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__transferSubmit4Response(soap, &_param_19);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__transferSubmit4Response(soap, &_param_19, "impltns:transferSubmit4Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__transferSubmit4Response(soap, &_param_19, "impltns:transferSubmit4Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__prioritySet(struct soap *soap)
{	struct impltns__prioritySet soap_tmp_impltns__prioritySet;
	struct impltns__prioritySetResponse _param_20;
	soap_default_impltns__prioritySetResponse(soap, &_param_20);
	soap_default_impltns__prioritySet(soap, &soap_tmp_impltns__prioritySet);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__prioritySet(soap, &soap_tmp_impltns__prioritySet, "impltns:prioritySet", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__prioritySet(soap, soap_tmp_impltns__prioritySet._jobId, soap_tmp_impltns__prioritySet._priority, _param_20);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__prioritySetResponse(soap, &_param_20);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__prioritySetResponse(soap, &_param_20, "impltns:prioritySetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__prioritySetResponse(soap, &_param_20, "impltns:prioritySetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__debugSet(struct soap *soap)
{	struct impltns__debugSet soap_tmp_impltns__debugSet;
	struct impltns__debugSetResponse _param_21;
	soap_default_impltns__debugSetResponse(soap, &_param_21);
	soap_default_impltns__debugSet(soap, &soap_tmp_impltns__debugSet);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__debugSet(soap, &soap_tmp_impltns__debugSet, "impltns:debugSet", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__debugSet(soap, soap_tmp_impltns__debugSet._source, soap_tmp_impltns__debugSet._destination, soap_tmp_impltns__debugSet._debug, _param_21);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__debugSetResponse(soap, &_param_21);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__debugSetResponse(soap, &_param_21, "impltns:debugSetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__debugSetResponse(soap, &_param_21, "impltns:debugSetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__blacklist(struct soap *soap)
{	struct impltns__blacklist soap_tmp_impltns__blacklist;
	struct impltns__blacklistResponse _param_22;
	soap_default_impltns__blacklistResponse(soap, &_param_22);
	soap_default_impltns__blacklist(soap, &soap_tmp_impltns__blacklist);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__blacklist(soap, &soap_tmp_impltns__blacklist, "impltns:blacklist", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__blacklist(soap, soap_tmp_impltns__blacklist._type, soap_tmp_impltns__blacklist._subject, soap_tmp_impltns__blacklist._blk, _param_22);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__blacklistResponse(soap, &_param_22);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__blacklistResponse(soap, &_param_22, "impltns:blacklistResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__blacklistResponse(soap, &_param_22, "impltns:blacklistResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__listRequests(struct soap *soap)
{	struct impltns__listRequests soap_tmp_impltns__listRequests;
	struct impltns__listRequestsResponse _param_23;
	soap_default_impltns__listRequestsResponse(soap, &_param_23);
	soap_default_impltns__listRequests(soap, &soap_tmp_impltns__listRequests);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__listRequests(soap, &soap_tmp_impltns__listRequests, "impltns:listRequests", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__listRequests(soap, soap_tmp_impltns__listRequests._inGivenStates, _param_23);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__listRequestsResponse(soap, &_param_23);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__listRequestsResponse(soap, &_param_23, "impltns:listRequestsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__listRequestsResponse(soap, &_param_23, "impltns:listRequestsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__listRequests2(struct soap *soap)
{	struct impltns__listRequests2 soap_tmp_impltns__listRequests2;
	struct impltns__listRequests2Response _param_24;
	soap_default_impltns__listRequests2Response(soap, &_param_24);
	soap_default_impltns__listRequests2(soap, &soap_tmp_impltns__listRequests2);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__listRequests2(soap, &soap_tmp_impltns__listRequests2, "impltns:listRequests2", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__listRequests2(soap, soap_tmp_impltns__listRequests2._inGivenStates, soap_tmp_impltns__listRequests2._forDN, soap_tmp_impltns__listRequests2._forVO, _param_24);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__listRequests2Response(soap, &_param_24);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__listRequests2Response(soap, &_param_24, "impltns:listRequests2Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__listRequests2Response(soap, &_param_24, "impltns:listRequests2Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getFileStatus(struct soap *soap)
{	struct impltns__getFileStatus soap_tmp_impltns__getFileStatus;
	struct impltns__getFileStatusResponse _param_25;
	soap_default_impltns__getFileStatusResponse(soap, &_param_25);
	soap_default_impltns__getFileStatus(soap, &soap_tmp_impltns__getFileStatus);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getFileStatus(soap, &soap_tmp_impltns__getFileStatus, "impltns:getFileStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getFileStatus(soap, soap_tmp_impltns__getFileStatus._requestID, soap_tmp_impltns__getFileStatus._offset, soap_tmp_impltns__getFileStatus._limit, _param_25);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getFileStatusResponse(soap, &_param_25);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getFileStatusResponse(soap, &_param_25, "impltns:getFileStatusResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getFileStatusResponse(soap, &_param_25, "impltns:getFileStatusResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getFileStatus2(struct soap *soap)
{	struct impltns__getFileStatus2 soap_tmp_impltns__getFileStatus2;
	struct impltns__getFileStatus2Response _param_26;
	soap_default_impltns__getFileStatus2Response(soap, &_param_26);
	soap_default_impltns__getFileStatus2(soap, &soap_tmp_impltns__getFileStatus2);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getFileStatus2(soap, &soap_tmp_impltns__getFileStatus2, "impltns:getFileStatus2", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getFileStatus2(soap, soap_tmp_impltns__getFileStatus2._requestID, soap_tmp_impltns__getFileStatus2._offset, soap_tmp_impltns__getFileStatus2._limit, _param_26);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getFileStatus2Response(soap, &_param_26);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getFileStatus2Response(soap, &_param_26, "impltns:getFileStatus2Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getFileStatus2Response(soap, &_param_26, "impltns:getFileStatus2Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getTransferJobStatus(struct soap *soap)
{	struct impltns__getTransferJobStatus soap_tmp_impltns__getTransferJobStatus;
	struct impltns__getTransferJobStatusResponse _param_27;
	soap_default_impltns__getTransferJobStatusResponse(soap, &_param_27);
	soap_default_impltns__getTransferJobStatus(soap, &soap_tmp_impltns__getTransferJobStatus);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getTransferJobStatus(soap, &soap_tmp_impltns__getTransferJobStatus, "impltns:getTransferJobStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getTransferJobStatus(soap, soap_tmp_impltns__getTransferJobStatus._requestID, _param_27);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getTransferJobStatusResponse(soap, &_param_27);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getTransferJobStatusResponse(soap, &_param_27, "impltns:getTransferJobStatusResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getTransferJobStatusResponse(soap, &_param_27, "impltns:getTransferJobStatusResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getTransferJobSummary(struct soap *soap)
{	struct impltns__getTransferJobSummary soap_tmp_impltns__getTransferJobSummary;
	struct impltns__getTransferJobSummaryResponse _param_28;
	soap_default_impltns__getTransferJobSummaryResponse(soap, &_param_28);
	soap_default_impltns__getTransferJobSummary(soap, &soap_tmp_impltns__getTransferJobSummary);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getTransferJobSummary(soap, &soap_tmp_impltns__getTransferJobSummary, "impltns:getTransferJobSummary", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getTransferJobSummary(soap, soap_tmp_impltns__getTransferJobSummary._requestID, _param_28);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getTransferJobSummaryResponse(soap, &_param_28);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getTransferJobSummaryResponse(soap, &_param_28, "impltns:getTransferJobSummaryResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getTransferJobSummaryResponse(soap, &_param_28, "impltns:getTransferJobSummaryResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getTransferJobSummary2(struct soap *soap)
{	struct impltns__getTransferJobSummary2 soap_tmp_impltns__getTransferJobSummary2;
	struct impltns__getTransferJobSummary2Response _param_29;
	soap_default_impltns__getTransferJobSummary2Response(soap, &_param_29);
	soap_default_impltns__getTransferJobSummary2(soap, &soap_tmp_impltns__getTransferJobSummary2);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getTransferJobSummary2(soap, &soap_tmp_impltns__getTransferJobSummary2, "impltns:getTransferJobSummary2", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getTransferJobSummary2(soap, soap_tmp_impltns__getTransferJobSummary2._requestID, _param_29);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getTransferJobSummary2Response(soap, &_param_29);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getTransferJobSummary2Response(soap, &_param_29, "impltns:getTransferJobSummary2Response", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getTransferJobSummary2Response(soap, &_param_29, "impltns:getTransferJobSummary2Response", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__cancel(struct soap *soap)
{	struct impltns__cancel soap_tmp_impltns__cancel;
	struct impltns__cancelResponse _param_30;
	soap_default_impltns__cancelResponse(soap, &_param_30);
	soap_default_impltns__cancel(soap, &soap_tmp_impltns__cancel);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__cancel(soap, &soap_tmp_impltns__cancel, "impltns:cancel", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__cancel(soap, soap_tmp_impltns__cancel._requestIDs, _param_30);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__cancelResponse(soap, &_param_30);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__cancelResponse(soap, &_param_30, "impltns:cancelResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__cancelResponse(soap, &_param_30, "impltns:cancelResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__setJobPriority(struct soap *soap)
{	struct impltns__setJobPriority soap_tmp_impltns__setJobPriority;
	struct impltns__setJobPriorityResponse _param_31;
	soap_default_impltns__setJobPriorityResponse(soap, &_param_31);
	soap_default_impltns__setJobPriority(soap, &soap_tmp_impltns__setJobPriority);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__setJobPriority(soap, &soap_tmp_impltns__setJobPriority, "impltns:setJobPriority", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__setJobPriority(soap, soap_tmp_impltns__setJobPriority._requestID, soap_tmp_impltns__setJobPriority._priority, _param_31);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__setJobPriorityResponse(soap, &_param_31);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__setJobPriorityResponse(soap, &_param_31, "impltns:setJobPriorityResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__setJobPriorityResponse(soap, &_param_31, "impltns:setJobPriorityResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__addVOManager(struct soap *soap)
{	struct impltns__addVOManager soap_tmp_impltns__addVOManager;
	struct impltns__addVOManagerResponse _param_32;
	soap_default_impltns__addVOManagerResponse(soap, &_param_32);
	soap_default_impltns__addVOManager(soap, &soap_tmp_impltns__addVOManager);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__addVOManager(soap, &soap_tmp_impltns__addVOManager, "impltns:addVOManager", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__addVOManager(soap, soap_tmp_impltns__addVOManager._VOName, soap_tmp_impltns__addVOManager._principal, _param_32);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__addVOManagerResponse(soap, &_param_32);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__addVOManagerResponse(soap, &_param_32, "impltns:addVOManagerResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__addVOManagerResponse(soap, &_param_32, "impltns:addVOManagerResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__removeVOManager(struct soap *soap)
{	struct impltns__removeVOManager soap_tmp_impltns__removeVOManager;
	struct impltns__removeVOManagerResponse _param_33;
	soap_default_impltns__removeVOManagerResponse(soap, &_param_33);
	soap_default_impltns__removeVOManager(soap, &soap_tmp_impltns__removeVOManager);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__removeVOManager(soap, &soap_tmp_impltns__removeVOManager, "impltns:removeVOManager", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__removeVOManager(soap, soap_tmp_impltns__removeVOManager._VOName, soap_tmp_impltns__removeVOManager._principal, _param_33);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__removeVOManagerResponse(soap, &_param_33);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__removeVOManagerResponse(soap, &_param_33, "impltns:removeVOManagerResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__removeVOManagerResponse(soap, &_param_33, "impltns:removeVOManagerResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__listVOManagers(struct soap *soap)
{	struct impltns__listVOManagers soap_tmp_impltns__listVOManagers;
	struct impltns__listVOManagersResponse _param_34;
	soap_default_impltns__listVOManagersResponse(soap, &_param_34);
	soap_default_impltns__listVOManagers(soap, &soap_tmp_impltns__listVOManagers);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__listVOManagers(soap, &soap_tmp_impltns__listVOManagers, "impltns:listVOManagers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__listVOManagers(soap, soap_tmp_impltns__listVOManagers._VOName, _param_34);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__listVOManagersResponse(soap, &_param_34);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__listVOManagersResponse(soap, &_param_34, "impltns:listVOManagersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__listVOManagersResponse(soap, &_param_34, "impltns:listVOManagersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getRoles(struct soap *soap)
{	struct impltns__getRoles soap_tmp_impltns__getRoles;
	struct impltns__getRolesResponse _param_35;
	soap_default_impltns__getRolesResponse(soap, &_param_35);
	soap_default_impltns__getRoles(soap, &soap_tmp_impltns__getRoles);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getRoles(soap, &soap_tmp_impltns__getRoles, "impltns:getRoles", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getRoles(soap, _param_35);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getRolesResponse(soap, &_param_35);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getRolesResponse(soap, &_param_35, "impltns:getRolesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getRolesResponse(soap, &_param_35, "impltns:getRolesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getRolesOf(struct soap *soap)
{	struct impltns__getRolesOf soap_tmp_impltns__getRolesOf;
	struct impltns__getRolesOfResponse _param_36;
	soap_default_impltns__getRolesOfResponse(soap, &_param_36);
	soap_default_impltns__getRolesOf(soap, &soap_tmp_impltns__getRolesOf);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getRolesOf(soap, &soap_tmp_impltns__getRolesOf, "impltns:getRolesOf", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getRolesOf(soap, soap_tmp_impltns__getRolesOf._otherDN, _param_36);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getRolesOfResponse(soap, &_param_36);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getRolesOfResponse(soap, &_param_36, "impltns:getRolesOfResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getRolesOfResponse(soap, &_param_36, "impltns:getRolesOfResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getVersion(struct soap *soap)
{	struct impltns__getVersion soap_tmp_impltns__getVersion;
	struct impltns__getVersionResponse _param_37;
	soap_default_impltns__getVersionResponse(soap, &_param_37);
	soap_default_impltns__getVersion(soap, &soap_tmp_impltns__getVersion);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getVersion(soap, &soap_tmp_impltns__getVersion, "impltns:getVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getVersion(soap, _param_37);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getVersionResponse(soap, &_param_37);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getVersionResponse(soap, &_param_37, "impltns:getVersionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getVersionResponse(soap, &_param_37, "impltns:getVersionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getSchemaVersion(struct soap *soap)
{	struct impltns__getSchemaVersion soap_tmp_impltns__getSchemaVersion;
	struct impltns__getSchemaVersionResponse _param_38;
	soap_default_impltns__getSchemaVersionResponse(soap, &_param_38);
	soap_default_impltns__getSchemaVersion(soap, &soap_tmp_impltns__getSchemaVersion);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getSchemaVersion(soap, &soap_tmp_impltns__getSchemaVersion, "impltns:getSchemaVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getSchemaVersion(soap, _param_38);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getSchemaVersionResponse(soap, &_param_38);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getSchemaVersionResponse(soap, &_param_38, "impltns:getSchemaVersionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getSchemaVersionResponse(soap, &_param_38, "impltns:getSchemaVersionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getInterfaceVersion(struct soap *soap)
{	struct impltns__getInterfaceVersion soap_tmp_impltns__getInterfaceVersion;
	struct impltns__getInterfaceVersionResponse _param_39;
	soap_default_impltns__getInterfaceVersionResponse(soap, &_param_39);
	soap_default_impltns__getInterfaceVersion(soap, &soap_tmp_impltns__getInterfaceVersion);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getInterfaceVersion(soap, &soap_tmp_impltns__getInterfaceVersion, "impltns:getInterfaceVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getInterfaceVersion(soap, _param_39);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getInterfaceVersionResponse(soap, &_param_39);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getInterfaceVersionResponse(soap, &_param_39, "impltns:getInterfaceVersionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getInterfaceVersionResponse(soap, &_param_39, "impltns:getInterfaceVersionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_impltns__getServiceMetadata(struct soap *soap)
{	struct impltns__getServiceMetadata soap_tmp_impltns__getServiceMetadata;
	struct impltns__getServiceMetadataResponse _param_40;
	soap_default_impltns__getServiceMetadataResponse(soap, &_param_40);
	soap_default_impltns__getServiceMetadata(soap, &soap_tmp_impltns__getServiceMetadata);
	soap->encodingStyle = NULL;
	if (!soap_get_impltns__getServiceMetadata(soap, &soap_tmp_impltns__getServiceMetadata, "impltns:getServiceMetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = impltns__getServiceMetadata(soap, soap_tmp_impltns__getServiceMetadata._key, _param_40);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_impltns__getServiceMetadataResponse(soap, &_param_40);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_impltns__getServiceMetadataResponse(soap, &_param_40, "impltns:getServiceMetadataResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impltns__getServiceMetadataResponse(soap, &_param_40, "impltns:getServiceMetadataResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_log__GetLog(struct soap *soap)
{	struct log__GetLog soap_tmp_log__GetLog;
	struct log__GetLogResponse _param_41;
	soap_default_log__GetLogResponse(soap, &_param_41);
	soap_default_log__GetLog(soap, &soap_tmp_log__GetLog);
	soap->encodingStyle = NULL;
	if (!soap_get_log__GetLog(soap, &soap_tmp_log__GetLog, "log:GetLog", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = log__GetLog(soap, soap_tmp_log__GetLog.jobId, _param_41);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_log__GetLogResponse(soap, &_param_41);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__GetLogResponse(soap, &_param_41, "log:GetLogResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__GetLogResponse(soap, &_param_41, "log:GetLogResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_log__GetLogInternal(struct soap *soap)
{	struct log__GetLogInternal soap_tmp_log__GetLogInternal;
	struct log__GetLogInternalResponse _param_42;
	soap_default_log__GetLogInternalResponse(soap, &_param_42);
	soap_default_log__GetLogInternal(soap, &soap_tmp_log__GetLogInternal);
	soap->encodingStyle = NULL;
	if (!soap_get_log__GetLogInternal(soap, &soap_tmp_log__GetLogInternal, "log:GetLogInternal", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = log__GetLogInternal(soap, soap_tmp_log__GetLogInternal.jobId, _param_42);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_log__GetLogInternalResponse(soap, &_param_42);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__GetLogInternalResponse(soap, &_param_42, "log:GetLogInternalResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__GetLogInternalResponse(soap, &_param_42, "log:GetLogInternalResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

} // namespace fts3


#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of fts3Server.cpp */
