#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
import unittest
from lib import base 


class TestCancel(base.TestBase):

	def test_cancelNoFinished(self):
		"""
		Cancelling a file that is still active/submitted must succeed
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer cancelling %s => %s" % (src, dst))
			self.surl.create(src)
			jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
			logging.info("Got job id %s" % jobId)
			self.client.cancel(jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual(state, 'CANCELED')


	def test_cancelTerminal(self):
		"""
		Cancelling a file that is in a terminal state must fail
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer cancelling terminal %s => %s" % (src, dst))
			self.surl.create(src)
			jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertRaises(Exception, self.client.cancel, jobId)


if __name__ == '__main__':
	import sys
	unittest.main(testRunner = unittest.TextTestRunner(stream=sys.stdout, verbosity = 2))

