#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestZeroedChecksum(base.TestBase):

	def test_headingZerosUserChecksum(self):
		"""
		The right checksum is given, but with heading 0.
		This is a regression test for LCGUTIL-216
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer zero-headed checksum %s => %s" % (src, dst))
			srcChecksum = self.surl.create(src)
			(al, val) = srcChecksum.split(':')
			zeroedChecksum = "%s:0%s" % (al, val)
			jobId = self.client.submit([{'sources': [src], 'destinations': [dst], 'checksums': [zeroedChecksum]}], ['-K', '-o'])
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual('FINISHED', state)



if __name__ == '__main__':
	import sys
	sys.exit(TestZeroedChecksum().run())

