#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
import unittest
from lib import cli, storage, surl 


class TestChecksum(unittest.TestCase):

	def __init__(self, *args, **kwargs): 
		super(TestChecksum, self).__init__(*args, **kwargs)
		self.surl   = surl.Surl()
		self.client = cli.Cli()


	def setUp(self):
		self.transfers = []
		for (srcSa, dstSa) in storage.getStoragePairs():
			srcSurl = self.surl.generate(srcSa)
			dstSurl = self.surl.generate(dstSa)
			self.transfers.append((srcSurl, dstSurl))


	def tearDown(self):
		allFiles = set(list(itertools.chain(*self.transfers)))
		for f in allFiles:
			try:
				logging.debug("Removing %s" % f)
				self.surl.unlink(f)
			except Exception, e:
				logging.error(e)


	def test_withChecksum(self):
		"""
		Just enable the flag needed to check the checksum
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer with checksum %s => %s" % (src, dst))
			srcChecksum = self.surl.create(src)
			jobId = self.client.submit(src, dst, ['-K'])
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual(state, 'FINISHED')
			dstChecksum = self.surl.checksum(dst)
			self.assertEqual(srcChecksum, dstChecksum)


	def test_withUserChecksum(self):
		"""
		Ask to validate the checksum and provide the right checksum
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer with user checksum %s => %s" % (src, dst))
			srcChecksum = self.surl.create(src)
			jobId = self.client.submit(src, dst, ['-K'], srcChecksum)
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual(state, 'FINISHED')
			dstChecksum = self.surl.checksum(dst)
			self.assertEqual(srcChecksum, dstChecksum)


	def test_withBadUserChecksum(self):
		"""
		Ask to validate the checksum but give a bad one on purpose
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer with wrong user checksum %s => %s" % (src, dst))
			srcChecksum = self.surl.create(src)
			shiftedChecksum = "%x" % (int(srcChecksum, 16) + 1)
			jobId = self.client.submit(src, dst, ['-K', '-o'], shiftedChecksum)
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual(state, 'FAILED')


if __name__ == '__main__':
	unittest.main()

