#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base

class FTSDebug(base.TestBase):

    def tearDown(self):
        for (src, dst) in self.transfers:
            self.client.setDebug(src, dst, 'off')

        base.TestBase.tearDown(self)
    def test_ftsDebug(self):
        """
        Setting sourse_se and dst_se ON
        """
        for (src, dst) in self.transfers:
            self.surl.create(src)
            self.client.setDebug(src, dst, 'on')
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FINISHED', state, 'job.state')


if __name__ == '__main__':
    import sys
    sys.exit(FTSDebug().run())
