#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestChecksum(base.TestBase):

	def test_withChecksum(self):
		"""
		Just enable the flag needed to check the checksum
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer with checksum %s => %s" % (src, dst))
			srcChecksum = self.surl.create(src)
			jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}], ['-K'])
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual('FINISHED', state)
			dstChecksum = self.surl.checksum(dst)
			self.assertEqual(srcChecksum, dstChecksum)



if __name__ == '__main__':
	import sys
	sys.exit(TestChecksum().run())

