#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestBigFileTransfer(base.TestBase):

    def test_tryToTransfer(self):
        """
        Trying to transfer a big file (200mb).
        It must succeed.
        """
        for (src, dst) in self.transfers:
            logging.info("Transfering file %s => %s" % (src, dst))
            self.surl.create(src, size = 209715200)
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FINISHED', state, 'job.state')



if __name__ == '__main__':
    import sys
    import os

    print os.environ

    sys.exit(TestBigFileTransfer().run())
