#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
import unittest
from lib import cli, storage, surl 


class TestCancel(unittest.TestCase):

	def __init__(self, *args, **kwargs): 
		super(TestCancel, self).__init__(*args, **kwargs)
		self.surl   = surl.Surl()
		self.client = cli.Cli()


	def setUp(self):
		self.transfers = []
		for (srcSa, dstSa) in storage.getStoragePairs():
			srcSurl = self.surl.generate(srcSa)
			dstSurl = self.surl.generate(dstSa)
			self.transfers.append((srcSurl, dstSurl))


	def tearDown(self):
		allFiles = set(list(itertools.chain(*self.transfers)))
		for f in allFiles:
			try:
				logging.debug("Removing %s" % f)
				self.surl.unlink(f)
			except Exception, e:
				logging.error(e)


	def test_cancelNoFinished(self):
		"""
		Cancelling a file that is still active/submitted must succeed
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer cancelling %s => %s" % (src, dst))
			self.surl.create(src)
			jobId = self.client.submit(src, dst)
			logging.info("Got job id %s" % jobId)
			self.client.cancel(jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual(state, 'CANCELED')


	def test_cancelTerminal(self):
		"""
		Cancelling a file that is in a terminal state must fail
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer cancelling terminal %s => %s" % (src, dst))
			self.surl.create(src)
			jobId = self.client.submit(src, dst)
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertRaises(Exception, self.client.cancel, jobId)


if __name__ == '__main__':
	unittest.main()

