#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestRetry(base.TestBase):

    def test_retry_not_retriable(self):
        """
        Submit a transfer that will fail with source does not exist. It must NOT be retried
        even if set.
        """
        for (src, dst) in self.transfers:
            logging.info("Retry transfer with non existing source %s => %s" % (src, dst))
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}],
                                       extraArgs = ['--retry', '2', '--retry-delay', '10'])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FAILED', state, 'job.state')

            files = self.client.getFileInfo(jobId)
            i = 0
            for pair in files.keys():
                fileLabel = 'job.files[' + str(i) + ']'
                self.assertEqual('FAILED', files[pair]['state'], fileLabel + '.state')
                self.assertEqual(0, int(files[pair]['retries']), fileLabel + '.retries')
                i += 1


    def test_retry_0(self):
        """
        Submit a transfer that will fail with an error that should be retried,
        but ask NOT TO retry, so there should be no retries
        """
        for (src, dst) in self.transfers:
            src = 'gsiftp://cern.ch:8443/path/file'
            logging.info("Retry transfer with non reachable source %s => %s" % (src, dst))
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}],
                                       extraArgs = ['--retry', '-1', '--retry-delay', '10'])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FAILED', state, 'job.state')

            files = self.client.getFileInfo(jobId)
            i = 0
            for pair in files.keys():
                fileLabel = 'job.files[' + str(i) + ']'
                self.assertEqual('FAILED', files[pair]['state'], fileLabel + '.state')
                self.assertEqual(0, int(files[pair]['retries']), fileLabel + '.retries')
                i += 1


    def test_retry(self):
        """
        Submit a transfer that will fail with an error that should be retried.
        """
        for (src, dst) in self.transfers:
            src = 'gsiftp://cern.ch:8443/path/file'
            logging.info("Retry transfer with non reachable source %s => %s" % (src, dst))
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}],
                                       extraArgs = ['--retry', '1', '--retry-delay', '10'])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FAILED', state, 'job.state')

            files = self.client.getFileInfo(jobId)
            i = 0
            for pair in files.keys():
                fileLabel = 'job.files[' + str(i) + ']'
                self.assertEqual('FAILED', files[pair]['state'], fileLabel + '.state')
                self.assertEqual(1, int(files[pair]['retries']), fileLabel + '.retries')
                i += 1


    def test_retry_detailed(self):
        """
        Submit a transfer with an error that should be retried.
        Query for detailed information (error reasons)
        """
        for (src, dst) in self.transfers:
            src = 'gsiftp://cern.ch:8443/path/file'
            logging.info("Retry transfer with non reachable source %s => %s" % (src, dst))
            jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}],
                                       extraArgs = ['--retry', '1', '--retry-delay', '10'])
            logging.info("Got job id %s" % jobId)
            state = self.client.poll(jobId)
            logging.info("Finished with %s" % state)
            self.assertEqual('FAILED', state, 'job.state')

            files = self.client.getFileInfo(jobId, detailed = True)
            i = 0
            for pair in files.keys():
                fileLabel = 'job.files[' + str(i) + ']'
                self.assertEqual('FAILED', files[pair]['state'], fileLabel + '.state')
                self.assertEqual(1, len(files[pair]['retries']), fileLabel + '.retries.length()')
                self.assertEqual(True, len(files[pair]['retries'][0]) > 0, fileLabel + '.retries[0] != ""')
                i += 1

if __name__ == '__main__':
    import sys
    sys.exit(TestRetry().run())

