#!/bin/bash

source fts3-common
source ../Macros
export source_TYPE="srm"
export dest_TYPE="srm"

    echo "fts3-bulk-submission"
    upload_test_file $CERN_SE1 # "1MB"

    get_source_file        
    get_dest_file
    echo "Source file=$source_file"
    echo "Dest file=$dest_file"
    
    echo "Will transmitted $NFILES files"
    bulk-transfer-k $source_file $dest_file $NFILES
    res=$?
    echo "Remove source file as GUID"
    GUID_file_deletion $GUID
            
    if [ $res != 0 ]; then
	echo "fts3-transfer-submit - Failed"
	
	if [ $res == 4 ]; then
	    TEST_FAILED "Transfer- time outed"
	fi
	TEST_FAILED " "
    fi
     echo "Check if files transferred"
     echo $dest_file | grep "srm" > /dev/null
     if [ $? == 0 ]; then
	echo "SRM dest files, Remove its"
        count=1
        while [ $count -le $NFILES ]
        do
    	    DST="$dest_file-$count"
            SURL_file_deletion $DST
    	    let  count=count+1
         done
    else
        echo "GSIFTP test files, check if exists"
        echo "Run: globus-url-copy -vb -list $dpm_SE2/"
        globus-url-copy -vb -list $dpm_SE2/ > message
        if [ $? != 0 ]; then
          TEST_FAILED "globus-url-copy -list - failed"
        fi
        #cat message
        count=1
        while [ $count -le $NFILES ]
        do
	    #echo "Count=$count"
            FF="$DPM_DST_FILE-$count"
            grep "$FF" message > /dev/null
            if [ $? != 0 ]; then
	        TEST_FAILED "file $FF - not exists"
    	    fi
            let count=count+1
        done     
        echo "All transmitted files Files - exist!"
    fi

    echo "OK"
    TEST_PASSED

exit 0	