#!/bin/bash
# meta: proxy=true
# meta: preconfig=../FTS3-config

source fts3-common
source ../Macros
export source_TYPE="gsiftp"
export dest_TYPE="gsiftp"  

    echo "fts3-list-submission"
    upload_test_file $CERN_SE1 # "1MB"

    get_source_file    
    get_dest_file

    echo "Source file=$source_file"
    echo "Dest file=$dest_file"

    list-transfer $source_file $dest_file
    res=$?
    echo "Remove source file as GUID"
    GUID_file_deletion $GUID
            
    if [ $res != 0 ]; then
    echo "fts3-transfer-submit - Failed"
    
    if [ $res == 4 ]; then
        TEST_FAILED "Transfer- time outed"
    fi
    TEST_FAILED " "
    fi
    echo "OK"
    TEST_PASSED

exit 0
