#!/bin/bash

source fts3-common
source ../Macros
export source_TYPE="srm"
export dest_TYPE="srm"

    echo "fts3-status"
    echo "1. File submission"
    upload_test_file $CERN_SE1 #"1MB"

    get_source_file
    get_dest_file    
    
    echo "Source file=$source_file"
    echo "Dest file=$dest_file"

    submit $source_file $dest_file
    res=$?
    if [ $res != 0 ]; then
	echo "fts3-transfer-submit - Failed"
	TEST_FAILED " "
    fi

    echo "OK"

    echo "2. Check STATUS , jobID= $JID"
    get_status_result $JID
    if [ $? == 1 ]; then
	TEST_FAILED "Unknown staus"
    fi 
    
    sleep 3
    get_status_result $JID
    if [ $? == 1 ]; then
	TEST_FAILED "Unknown status"
    fi
    poll_status_with_timeout $JID $TIME_OUT
    
    echo "Remove source file as GUID"
    GUID_file_deletion $GUID
    echo "Check if SRM file"
    
    echo $dest_file | grep "srm" >/dev/null
    if [ $? == 0 ];then
        SURL_file_deletion $dest_file
    fi
                                    
    TEST_PASSED

exit 0