--
-- FTS3 Schema 6.0.0
-- Schema changes for OIDC integration
-- 

ALTER TABLE `t_job` 
	ADD COLUMN `target_qos` varchar(255);
ALTER TABLE `t_job` 
	MODIFY COLUMN job_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','FINISHEDDIRTY','CANCELED','DELETE') NOT NULL;

ALTER TABLE `t_job_backup` 
	MODIFY COLUMN job_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','FINISHEDDIRTY','CANCELED','DELETE') NOT NULL;
ALTER TABLE `t_job_backup` 
	ADD COLUMN `target_qos` varchar(255);

ALTER TABLE `t_file` 
	MODIFY COLUMN file_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','STARTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','CANCELED','NOT_USED','ON_HOLD','ON_HOLD_STAGING') NOT NULL;
ALTER TABLE `t_file_backup` 
	MODIFY COLUMN file_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','STARTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','CANCELED','NOT_USED','ON_HOLD','ON_HOLD_STAGING') NOT NULL;

INSERT INTO t_schema_vers (major, minor, patch, message)
VALUES (6, 0, 0, 'OIDC integration diff');
