--
-- FTS3 Schema 5.0.0
-- [FTS-1042] Create an extra STATE named QOS_TRANSITION on t_job, t_file, t_file_backup, t_job_backup
--

ALTER TABLE t_job MODIFY COLUMN job_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','FINISHEDDIRTY','CANCELED','DELETE') NOT NULL;
ALTER TABLE t_file MODIFY COLUMN file_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','STARTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','CANCELED','NOT_USED','ON_HOLD','ON_HOLD_STAGING') NOT NULL;
ALTER TABLE t_file_backup MODIFY COLUMN file_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','STARTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','CANCELED','NOT_USED','ON_HOLD','ON_HOLD_STAGING') NOT NULL;
ALTER TABLE t_job_backup MODIFY COLUMN job_state enum('STAGING','QOS_TRANSITION','QOS_REQUEST_SUBMITTED','SUBMITTED','READY','ACTIVE','FINISHED','FAILED','FINISHEDDIRTY','CANCELED','DELETE') NOT NULL;

ALTER TABLE t_job ADD target_qos varchar(255) DEFAULT NULL;
ALTER TABLE t_job_backup ADD target_qos varchar(255) DEFAULT NULL;

CREATE TABLE t_oauth2_providers (
    `provider_url` VARCHAR(150) NOT NULL,
    `provider_jwk`   VARCHAR(150) NOT NULL,
    PRIMARY KEY(`provider_url`)
)