#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestBigFileTransfer(base.TestRepeatEach):

    def test_tryToTransfer(self, transfer):
        """
        Trying to transfer a big file (200mb).
        It must succeed.
        """
        src, dst = transfer
        logging.info("Transfering file %s => %s" % (src, dst))
        self.surl.create(src, size = 209715200)
        jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
        logging.info("Got job id %s" % jobId)
        state = self.client.poll(jobId)
        logging.info("Finished with %s" % state)
        self.assertEqual('FINISHED', state, 'job.state')


if __name__ == '__main__':
    import sys
    sys.exit(TestBigFileTransfer().run())
