#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestRestDelegate(base.TestBase):

    def test_redelegate(self):
        """
        Force the redelegation, as the proxy delegated by the
        soap interface may not work
        """
        logging.info("Force redelegation")
        self.client.redelegate(force=True)


if __name__ == '__main__':
    import sys
    sys.exit(TestRestDelegate().run())
