#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestOverwrite(base.TestBase):

	def test_overwriteExisting(self):
		"""
		Enable overwrite and submit a transfer with a file that does exist.
		It must succeed.
		"""
		for (src, dst) in self.transfers:
			logging.info("Transfer overwriting existing file %s => %s" % (src, dst))
			self.surl.create(src)
			self.surl.create(dst)
			jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}], ['-o'])
			logging.info("Got job id %s" % jobId)
			state = self.client.poll(jobId)
			logging.info("Finished with %s" % state)
			self.assertEqual('FINISHED', state, 'job.state')



if __name__ == '__main__':
	import sys
	sys.exit(TestOverwrite().run())
