#!/usr/bin/env python
# meta: proxy=true
# meta: preconfig=../FTS3-config
import itertools
import logging
from lib import base 


class TestOverwriteDont(base.TestRepeatEach):

    def test_noOverwriteExisting(self, transfer):
        """
        Do NOT enable overwrite and submit a transfer with a file that does exist.
        It must fail.
        """
        src, dst = transfer
        logging.info("Transfer NOT overwriting existing file %s => %s" % (src, dst))
        self.surl.create(src)
        self.surl.create(dst)
        jobId = self.client.submit([{'sources': [src], 'destinations': [dst]}])
        logging.info("Got job id %s" % jobId)
        state = self.client.poll(jobId)
        logging.info("Finished with %s" % state)
        self.assertEqual('FAILED', state, 'job.state')


if __name__ == '__main__':
    import sys
    sys.exit(TestOverwriteDont().run())
