#!/bin/bash
source ../Macros
source rest-common

echo "curl-job-status"
copyToDPM 
if [ $? != 0 ]; then
  TEST_FAILED "Source file is not copied"
fi
                                                            
get_source_file        
get_dest_file

dest_file="${dest_file}-status-`mktemp -u XXXXXX`"

echo "Source file=$source_file"
echo "Dest file=$dest_file"
echo "Curl submission"

submit $source_file $dest_file
if [ $? != 0 ]; then
  echo "submit - Failed (Exit code)"
  TEST_FAILED "submit - Failed (Exit code)"
fi

echo "JobID=$JID"
echo "Check status jobiD"
get_status_result $JID
res=$?
if [ "$res" -eq 1 ]; then
  TEST_FAILED "Error retrieving the status with get_status_result()"
fi

if [ "$res" -eq 99 ]; then
  TEST_FAILED "Exit code  != 0"
fi

echo "Status - valid, cancel this job"
job-cancel $JID
echo "Remove file $dest_file"
edg-gridftp-rm $dest_file
    
    
TEST_PASSED

