#!/bin/bash
source ../Macros
source rest-common

export source_TYPE="gsiftp"
export dest_TYPE="gsiftp"  

echo "curl-submission"
copyToDPM  #"1MB"
if [ $? != 0 ]; then
  TEST_FAILED "Source file is not copied"
fi

get_source_file
get_dest_file

dest_file=$dest_file-`mktemp -u XXXXXX`

echo "Preliminary check if exists and remove $dest_file file"
edg-gridftp-exists $dest_file
if [ $? == 0 ]; then
	echo "Dest file exists, remove it"
	edg-gridftp-rm $dest_file
fi

echo "Source file=$source_file"
echo "Dest file=$dest_file"

echo "Curl submission"
curl_transfer $source_file $dest_file
res=$?
if [ $res != 0 ]; then
 echo "curl-transfer - Failed"
 if [ $res == 4 ]; then
  job-cancel $JID
  TEST_FAILED "Transfer- time outed,status=$STATUS, job $JID cancelled"
 fi
 if [ $res == 99 ]; then
  TEST_FAILED "curl-job-status: exit code != 0"
 fi
 TEST_FAILED "curl-transfer() - failed: exit=$res, STATUS=$STATUS "
fi

echo "Check if files transferred"

echo "Check if exists"
echo "Run: edg-gridftp-exists $dest_file"
edg-gridftp-exists $dest_file
if [ $? != 0 ]; then
   TEST_WARN "file $dest_file - not exists"
fi
edg-gridftp-rm $dest_file
echo "Removed: $dest_file"

TEST_PASSED

