#!/bin/bash
source ../Macros

echo "Run: curl -s --capath /etc/grid-security/certificates/ --cert $X509_USER_PROXY --key $X509_USER_PROXY --cacert $X509_USER_PROXY https://$FTS3_HOST:$FTS3_REST_PORT/whoami"
response=`curl -s --capath /etc/grid-security/certificates/ \
               --cert $X509_USER_PROXY --key $X509_USER_PROXY --cacert $X509_USER_PROXY \
               https://$FTS3_HOST:$FTS3_REST_PORT/whoami`



if [ $? != 0 ]; then
  TEST_FAILED "Bad exit code"
fi

DN=`voms-proxy-info -identity`
echo "$response" | grep "$DN" -q
if [ $? != 0 ]; then
  echo "$response"
  TEST_FAILED "Expected DN not present!"
fi

TEST_PASSED

