.TH "CliManager" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CliManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetInterface\fP (string interface)"
.br
.ti -1c
.RI "string \fBgetPassword\fP ()"
.br
.ti -1c
.RI "int \fBisChecksumSupported\fP ()"
.br
.ti -1c
.RI "int \fBisDelegationSupported\fP ()"
.br
.ti -1c
.RI "int \fBisRolesOfSupported\fP ()"
.br
.ti -1c
.RI "int \fBisSetTCPBufferSupported\fP ()"
.br
.ti -1c
.RI "int \fBisExtendedChannelListSupported\fP ()"
.br
.ti -1c
.RI "int \fBisChannelMessageSupported\fP ()"
.br
.ti -1c
.RI "int \fBisUserVoRestrictListingSupported\fP ()"
.br
.ti -1c
.RI "int \fBisVersion330StatesSupported\fP ()"
.br
.ti -1c
.RI "int \fBisItVersion330\fP ()"
.br
.ti -1c
.RI "int \fBisItVersion340\fP ()"
.br
.ti -1c
.RI "int \fBisItVersion350\fP ()"
.br
.ti -1c
.RI "int \fBisItVersion370\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCliManager\fP * \fBgetInstance\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "string \fBFTS3_PARAM_GRIDFTP\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_MYPROXY\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_DELEGATIONID\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_SPACETOKEN\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_SPACETOKEN_SOURCE\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_COPY_PIN_LIFETIME\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_LAN_CONNECTION\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_FAIL_NEARLINE\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_OVERWRITEFLAG\fP"
.br
.ti -1c
.RI "string \fBFTS3_PARAM_CHECKSUM_METHOD\fP"
.br
.ti -1c
.RI "string \fBFTS3_CA_SD_TYPE\fP"
.br
.ti -1c
.RI "string \fBFTS3_SD_ENV\fP"
.br
.ti -1c
.RI "string \fBFTS3_SD_TYPE\fP"
.br
.ti -1c
.RI "string \fBFTS3_IFC_VERSION\fP"
.br
.ti -1c
.RI "string \fBFTS3_INTERFACE_VERSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file CliManager.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
