.TH "FileTransferSoapBindingProxy" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTransferSoapBindingProxy \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTransferSoapBindingProxy\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fBFileTransferSoapBindingProxy\fP (const struct soap &)"
.br
.RI "\fIConstructor with copy of another engine state. \fP"
.ti -1c
.RI "\fBFileTransferSoapBindingProxy\fP (soap_mode iomode)"
.br
.RI "\fIConstructor with engine input+output mode control. \fP"
.ti -1c
.RI "\fBFileTransferSoapBindingProxy\fP (soap_mode imode, soap_mode omode)"
.br
.RI "\fIConstructor with engine input and output mode control. \fP"
.ti -1c
.RI "virtual \fB~FileTransferSoapBindingProxy\fP ()"
.br
.RI "\fIDestructor frees deserialized data. \fP"
.ti -1c
.RI "virtual void \fBFileTransferSoapBindingProxy_init\fP (soap_mode imode, soap_mode omode)"
.br
.RI "\fIInitializer used by constructor. \fP"
.ti -1c
.RI "virtual void \fBsoap_noheader\fP ()"
.br
.RI "\fIDisables and removes SOAP Header from message. \fP"
.ti -1c
.RI "virtual const \fBSOAP_ENV__Fault\fP * \fBsoap_fault\fP ()"
.br
.RI "\fIGet SOAP Fault structure (NULL when absent) \fP"
.ti -1c
.RI "virtual const char * \fBsoap_fault_string\fP ()"
.br
.RI "\fIGet SOAP Fault string (NULL when absent) \fP"
.ti -1c
.RI "virtual const char * \fBsoap_fault_detail\fP ()"
.br
.RI "\fIGet SOAP Fault detail as string (NULL when absent) \fP"
.ti -1c
.RI "virtual int \fBsoap_close_socket\fP ()"
.br
.RI "\fIForce close connection (normally automatic, except for send_X ops) \fP"
.ti -1c
.RI "virtual void \fBsoap_print_fault\fP (FILE *)"
.br
.RI "\fIPrint fault. \fP"
.ti -1c
.RI "virtual void \fBsoap_stream_fault\fP (std::ostream &)"
.br
.RI "\fIPrint fault to stream. \fP"
.ti -1c
.RI "virtual char * \fBsoap_sprint_fault\fP (char *buf, size_t len)"
.br
.RI "\fIPut fault into buffer. \fP"
.ti -1c
.RI "virtual int \fBplacementSubmit\fP (\fBtransfer__PlacementJob\fP *_job, struct \fBfts__placementSubmitResponse\fP &_param_1)"
.br
.RI "\fIWeb service operation 'placementSubmit' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBplacementSubmit2\fP (\fBtransfer__PlacementJob\fP *_job, struct \fBfts__placementSubmit2Response\fP &_param_2)"
.br
.RI "\fIWeb service operation 'placementSubmit2' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBtransferSubmit\fP (\fBtransfer__TransferJob\fP *_job, struct \fBfts__transferSubmitResponse\fP &_param_3)"
.br
.RI "\fIWeb service operation 'transferSubmit' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBtransferSubmit2\fP (\fBtransfer__TransferJob\fP *_job, struct \fBfts__transferSubmit2Response\fP &_param_4)"
.br
.RI "\fIWeb service operation 'transferSubmit2' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBtransferSubmit3\fP (\fBtransfer__TransferJob2\fP *_job, struct \fBfts__transferSubmit3Response\fP &_param_5)"
.br
.RI "\fIWeb service operation 'transferSubmit3' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBsubmit\fP (\fBtransfer__TransferJob\fP *_job, struct \fBfts__submitResponse\fP &_param_6)"
.br
.RI "\fIWeb service operation 'submit' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBlistRequests\fP (\fBfts__ArrayOf_USCOREsoapenc_USCOREstring\fP *_inGivenStates, struct \fBfts__listRequestsResponse\fP &_param_7)"
.br
.RI "\fIWeb service operation 'listRequests' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBlistRequests2\fP (\fBfts__ArrayOf_USCOREsoapenc_USCOREstring\fP *_inGivenStates, std::string _forDN, std::string _forVO, struct \fBfts__listRequests2Response\fP &_param_8)"
.br
.RI "\fIWeb service operation 'listRequests2' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetFileStatus\fP (std::string _requestID, int _offset, int _limit, struct \fBfts__getFileStatusResponse\fP &_param_9)"
.br
.RI "\fIWeb service operation 'getFileStatus' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetFileStatus2\fP (std::string _requestID, int _offset, int _limit, struct \fBfts__getFileStatus2Response\fP &_param_10)"
.br
.RI "\fIWeb service operation 'getFileStatus2' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetTransferJobStatus\fP (std::string _requestID, struct \fBfts__getTransferJobStatusResponse\fP &_param_11)"
.br
.RI "\fIWeb service operation 'getTransferJobStatus' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetTransferJobSummary\fP (std::string _requestID, struct \fBfts__getTransferJobSummaryResponse\fP &_param_12)"
.br
.RI "\fIWeb service operation 'getTransferJobSummary' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetTransferJobSummary2\fP (std::string _requestID, struct \fBfts__getTransferJobSummary2Response\fP &_param_13)"
.br
.RI "\fIWeb service operation 'getTransferJobSummary2' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBcancel\fP (\fBfts__ArrayOf_USCOREsoapenc_USCOREstring\fP *_requestIDs, struct \fBfts__cancelResponse\fP &_param_14)"
.br
.RI "\fIWeb service operation 'cancel' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBsetJobPriority\fP (std::string _requestID, int _priority, struct \fBfts__setJobPriorityResponse\fP &_param_15)"
.br
.RI "\fIWeb service operation 'setJobPriority' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBaddVOManager\fP (std::string _VOName, std::string _principal, struct \fBfts__addVOManagerResponse\fP &_param_16)"
.br
.RI "\fIWeb service operation 'addVOManager' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBremoveVOManager\fP (std::string _VOName, std::string _principal, struct \fBfts__removeVOManagerResponse\fP &_param_17)"
.br
.RI "\fIWeb service operation 'removeVOManager' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBlistVOManagers\fP (std::string _VOName, struct \fBfts__listVOManagersResponse\fP &_param_18)"
.br
.RI "\fIWeb service operation 'listVOManagers' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetRoles\fP (struct \fBfts__getRolesResponse\fP &_param_19)"
.br
.RI "\fIWeb service operation 'getRoles' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetRolesOf\fP (std::string _otherDN, struct \fBfts__getRolesOfResponse\fP &_param_20)"
.br
.RI "\fIWeb service operation 'getRolesOf' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetVersion\fP (struct \fBfts__getVersionResponse\fP &_param_21)"
.br
.RI "\fIWeb service operation 'getVersion' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetSchemaVersion\fP (struct \fBfts__getSchemaVersionResponse\fP &_param_22)"
.br
.RI "\fIWeb service operation 'getSchemaVersion' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetInterfaceVersion\fP (struct \fBfts__getInterfaceVersionResponse\fP &_param_23)"
.br
.RI "\fIWeb service operation 'getInterfaceVersion' (returns error code or SOAP_OK) \fP"
.ti -1c
.RI "virtual int \fBgetServiceMetadata\fP (std::string _key, struct \fBfts__getServiceMetadataResponse\fP &_param_24)"
.br
.RI "\fIWeb service operation 'getServiceMetadata' (returns error code or SOAP_OK) \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBsoap_endpoint\fP"
.br
.RI "\fIEndpoint URL of service 'FileTransferSoapBindingProxy' (change as needed) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ftsFileTransferSoapBindingProxy.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
