.TH "FileTransferSoapBinding" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTransferSoapBinding \- .TH "FileTransferSoapBinding" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTransferSoapBinding \- .SH "Operations of Binding  'FileTransferSoapBinding'"
.PP
.IP "\(bu" 2
\fBfts__placementSubmit\fP
.IP "\(bu" 2
\fBfts__placementSubmit2\fP
.IP "\(bu" 2
\fBfts__transferSubmit\fP
.IP "\(bu" 2
\fBfts__transferSubmit2\fP
.IP "\(bu" 2
\fBfts__transferSubmit3\fP
.IP "\(bu" 2
\fBfts__submit\fP
.IP "\(bu" 2
\fBfts__listRequests\fP
.IP "\(bu" 2
\fBfts__listRequests2\fP
.IP "\(bu" 2
\fBfts__getFileStatus\fP
.IP "\(bu" 2
\fBfts__getFileStatus2\fP
.IP "\(bu" 2
\fBfts__getTransferJobStatus\fP
.IP "\(bu" 2
\fBfts__getTransferJobSummary\fP
.IP "\(bu" 2
\fBfts__getTransferJobSummary2\fP
.IP "\(bu" 2
\fBfts__cancel\fP
.IP "\(bu" 2
\fBfts__setJobPriority\fP
.IP "\(bu" 2
\fBfts__addVOManager\fP
.IP "\(bu" 2
\fBfts__removeVOManager\fP
.IP "\(bu" 2
\fBfts__listVOManagers\fP
.IP "\(bu" 2
\fBfts__getRoles\fP
.IP "\(bu" 2
\fBfts__getRolesOf\fP
.IP "\(bu" 2
\fBfts__getVersion\fP
.IP "\(bu" 2
\fBfts__getSchemaVersion\fP
.IP "\(bu" 2
\fBfts__getInterfaceVersion\fP
.IP "\(bu" 2
\fBfts__getServiceMetadata\fP
.PP
.SH "Endpoints of Binding  'FileTransferSoapBinding'"
.PP
.IP "\(bu" 2
https://localhost:8443/glite-data-transfer-interface/FileTransfer
.PP
.PP
Note: use wsdl2h option -N to change the service binding prefix name 
