.TH "fts__placementSubmit2Response" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fts__placementSubmit2Response \- 
.PP
Operation response struct 'fts__placementSubmit2Response' of service binding 'FileTransferSoapBinding' operation 'fts__placementSubmit2'.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fB_placementSubmit2Return\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Operation response struct 'fts__placementSubmit2Response' of service binding 'FileTransferSoapBinding' operation 'fts__placementSubmit2'. 
.PP
Definition at line 679 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
