.TH "fts__getFileStatusResponse" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fts__getFileStatusResponse \- 
.PP
Operation response struct 'fts__getFileStatusResponse' of service binding 'FileTransferSoapBinding' operation 'fts__getFileStatus'.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfts__ArrayOf_USCOREtns3_USCOREFileTransferStatus\fP * \fB_getFileStatusReturn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Operation response struct 'fts__getFileStatusResponse' of service binding 'FileTransferSoapBinding' operation 'fts__getFileStatus'. 
.PP
Definition at line 1154 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
