.TH "fts__getRoles" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fts__getRoles \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 986 of file ftsStub.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
