.TH "fts__listVOManagersResponse" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fts__listVOManagersResponse \- 
.PP
Operation response struct 'fts__listVOManagersResponse' of service binding 'FileTransferSoapBinding' operation 'fts__listVOManagers'.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfts__ArrayOf_USCOREsoapenc_USCOREstring\fP * \fB_listVOManagersReturn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Operation response struct 'fts__listVOManagersResponse' of service binding 'FileTransferSoapBinding' operation 'fts__listVOManagers'. 
.PP
Definition at line 1780 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
