.TH "fts__getRolesOfResponse" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fts__getRolesOfResponse \- 
.PP
Operation response struct 'fts__getRolesOfResponse' of service binding 'FileTransferSoapBinding' operation 'fts__getRolesOf'.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtransfer__Roles\fP * \fB_getRolesOfReturn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Operation response struct 'fts__getRolesOfResponse' of service binding 'FileTransferSoapBinding' operation 'fts__getRolesOf'. 
.PP
Definition at line 1907 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
