.TH "SOAP_ENV__Fault" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOAP_ENV__Fault \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfaultcode\fP"
.br
.ti -1c
.RI "char * \fBfaultstring\fP"
.br
.ti -1c
.RI "char * \fBfaultactor\fP"
.br
.ti -1c
.RI "struct \fBSOAP_ENV__Detail\fP * \fBdetail\fP"
.br
.ti -1c
.RI "struct \fBSOAP_ENV__Code\fP * \fBSOAP_ENV__Code\fP"
.br
.ti -1c
.RI "struct \fBSOAP_ENV__Reason\fP * \fBSOAP_ENV__Reason\fP"
.br
.ti -1c
.RI "char * \fBSOAP_ENV__Node\fP"
.br
.ti -1c
.RI "char * \fBSOAP_ENV__Role\fP"
.br
.ti -1c
.RI "struct \fBSOAP_ENV__Detail\fP * \fBSOAP_ENV__Detail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1149 of file ftsStub.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
