.TH "SOAP_ENV__Code" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOAP_ENV__Code \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBSOAP_ENV__Value\fP"
.br
.ti -1c
.RI "struct \fBSOAP_ENV__Code\fP * \fBSOAP_ENV__Subcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1116 of file ftsStub.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
