.TH "SubmitTransferCli" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubmitTransferCli \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCliBase\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtransfer__TransferParams\fP * \fBgetParams\fP (soap *soap)"
.br
.ti -1c
.RI "bool \fBperformChecks\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitCli\fP (int ac, char *av[])"
.br
.ti -1c
.RI "string \fBgetPassword\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file SubmitTransferCli.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
