.TH "transfer__CannotCancelException" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transfer__CannotCancelException \- 
.PP
'http://transfer.data.glite.org':CannotCancelException is a complexType with complexContent extension of 'http://transfer.data.glite.org':TransferException.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.PP
Inherits \fBtransfer__TransferException\fP, and \fBtransfer__TransferException\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBsoap_type\fP () const "
.br
.ti -1c
.RI "virtual void \fBsoap_default\fP (struct \fBsoap\fP *)"
.br
.ti -1c
.RI "virtual void \fBsoap_serialize\fP (struct \fBsoap\fP *) const "
.br
.ti -1c
.RI "virtual int \fBsoap_put\fP (struct \fBsoap\fP *, const char *, const char *) const "
.br
.ti -1c
.RI "virtual int \fBsoap_out\fP (struct \fBsoap\fP *, const char *, int, const char *) const "
.br
.ti -1c
.RI "virtual void * \fBsoap_get\fP (struct \fBsoap\fP *, const char *, const char *)"
.br
.ti -1c
.RI "virtual void * \fBsoap_in\fP (struct \fBsoap\fP *, const char *, const char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
'http://transfer.data.glite.org':CannotCancelException is a complexType with complexContent extension of 'http://transfer.data.glite.org':TransferException. 
.PP
Definition at line 500 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
