.TH "transfer__TransferException" 3 "Wed Feb 8 2012" "Version 0.0.0" "EMI File Transfer Service (FTS 3)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transfer__TransferException \- 
.PP
'http://transfer.data.glite.org':TransferException is a complexType.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fts3-transfer-submit.h>\fP
.PP
Inherited by \fBtransfer__AuthorizationException\fP, \fBtransfer__AuthorizationException\fP, \fBtransfer__CannotCancelException\fP, \fBtransfer__CannotCancelException\fP, \fBtransfer__ExistsException\fP, \fBtransfer__ExistsException\fP, \fBtransfer__InternalException\fP, \fBtransfer__InternalException\fP, \fBtransfer__InvalidArgumentException\fP, \fBtransfer__InvalidArgumentException\fP, \fBtransfer__NotExistsException\fP, \fBtransfer__NotExistsException\fP, \fBtransfer__ServiceBusyException\fP, and \fBtransfer__ServiceBusyException\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBsoap_type\fP () const "
.br
.ti -1c
.RI "virtual void \fBsoap_default\fP (struct \fBsoap\fP *)"
.br
.ti -1c
.RI "virtual void \fBsoap_serialize\fP (struct \fBsoap\fP *) const "
.br
.ti -1c
.RI "virtual int \fBsoap_put\fP (struct \fBsoap\fP *, const char *, const char *) const "
.br
.ti -1c
.RI "virtual int \fBsoap_out\fP (struct \fBsoap\fP *, const char *, int, const char *) const "
.br
.ti -1c
.RI "virtual void * \fBsoap_get\fP (struct \fBsoap\fP *, const char *, const char *)"
.br
.ti -1c
.RI "virtual void * \fBsoap_in\fP (struct \fBsoap\fP *, const char *, const char *)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string * \fBmessage\fP"
.br
.RI "\fIElement message of type xs:string. \fP"
.ti -1c
.RI "struct \fBsoap\fP * \fBsoap\fP"
.br
.RI "\fIA handle to the soap struct that manages this instance (automatically set) \fP"
.in -1c
.SH "Detailed Description"
.PP 
'http://transfer.data.glite.org':TransferException is a complexType. 
.PP
Definition at line 181 of file fts3-transfer-submit.h.
.SH "Field Documentation"
.PP 
.SS "std::string * \fBtransfer__TransferException::message\fP"
.PP
Element message of type xs:string. Nullable pointer. 
.PP
Definition at line 184 of file fts3-transfer-submit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMI File Transfer Service (FTS 3) from the source code.
