.\" Manpage for fts_db_cleaner.
.\" Contact fts-devel@cern.ch for any corrections.
.TH man 8 "23 May 2013" "1.0" "fts_db_cleaner man page"
.SH NAME
fts_db_cleaner
.SH SYNOPSIS
Starts a cron job that periodically cleans up the database, old transfer-jobs are being moved to history tables.
.SH SEE ALSO
http://fts3-service.web.cern.ch/
