.\" Manpage for fts_server.
.\" Contact fts-devel@cern.ch for any corrections.
.TH man 1 "09 July 2012" "1.0" "fts_server man page"
.SH NAME
fts_server
.SH SYNOPSIS
fts_server [options]
.SH DESCRIPTION
fts_server starts the FTS3 server. 
.SH OPTIONS
  -h [ --help ]         Print this help text and exit.
  -q [ --quiet ]        Quiet operation.
  -v [ --verbose ]      Be more verbose.
  -s [ --service ] arg  Use the transfer service at the specified URL.
  -r [--rush]           Quick start and stop. Not intended for production.
  -V [ --version ]      Print the version number and exit.
.SH SEE ALSO
http://fts3-service.web.cern.ch/
