.\" Manpage for fts_optimizer.
.\" Contact fts-devel@cern.ch for any corrections.
.TH man 8 "12 Aug 2024" "1.0" "fts_optimizer man page"
.SH NAME
fts_optimizer
.SH SYNOPSIS
Starts the FTS Optimizer daemon, core component of the FTS server responsible for deciding how many parallel transfers should go on a given link.
The Optimizer takes into account the current and previous throughput history, as well as recent success rates when taking its decision.
.SH SEE ALSO
https://fts.web.cern.ch/
