.\" Manpage for fts_msg_bulk.
.\" Contact fts-devel@cern.ch for any corrections.
.TH man 8 "23 May 2013" "1.0" "fts_msg_bulk"
.SH NAME
fts_msg_bulk
.SH SYNOPSIS
Starts a cron job that carries out the task of publishing monitoring messages for each individual file transfer.
.SH SEE ALSO
http://fts3-service.web.cern.ch/
