.\" Manpage for fts_qos.
.\" Contact fts-devel@cern.ch for any corrections.
.TH man 8 "02 Dec 2020" "1.0" "fts_qos man page"
.SH NAME
fts_qos
.SH SYNOPSIS
Starts the FTS QoS daemon, core component of the FTS server responsible with handling Staging and Archive poll operations.
.SH SEE ALSO
https://fts.web.cern.ch/
