.\" Manpage for fts-transfer-submit.
.\" Contact michal.simon@cern.ch to correct errors or typos.
.TH man 1 "09 July 2012" "1.0" "fts-transfer-submit man page"
.SH NAME
fts-transfer-submit
.SH SYNOPSIS
fts-transfer-submit [options] SOURCE DEST [CHECKSUM]
.SH DESCRIPTION
fts-transfer-submit is a tool for submitting transfer-jobs using the GRID File Transfer Service 3. The user has to specify the source and destination, optionally the checksum may be specified (Algorithm:Value) 
.SH OPTIONS
  -h [ --help ]         Print this help text and exit.
  -q [ --quiet ]        Quiet operation.
  -v [ --verbose ]      Be more verbose.
  -s [ --service ] arg  Use the transfer service at the specified URL.
  --proxy arg           Path to the proxy certificate (e.g. /tmp/x509up_u500).
  -V [ --version ]      Print the version number and exit.
  -j [ --json ]         The output should be printed in JSON format

  --capath arg          Path to the GRID security certificates 

  --source arg          Specify source site name.
  --destination arg     Specify destination site name.
  -I [ --id ] arg       Delegation with ID as the delegation identifier.
  -e [ --expire ] arg   Expiration time of the delegation in minutes.
  -b [ --blocking ]     Blocking mode, wait until the operation completes.
  -f [ --file ] arg     Name of a the bulk submission file.
  -g [ --gparam ] arg   Deprecated. For compatibility only.
  -i [ --interval ] arg Interval between two poll operations in blocking mode.
  -o [ --overwrite ]    Overwrite files.

  -t [ --dest-token ] arg    The destination space token
  -S [ --source-token ] arg  The source space token

  -K [ --compare-checksums ] Compare checksums between source and destination.

  --copy-pin-lifetime (=-1) Pin lifetime of the copy of the file (seconds).
  --bring-online (=-1)      Bring online timeout expressed in seconds.

  -r [ --reuse ]            Enable session reuse for the transfer job
  -m [ --multi-hop ]        Enable multi-hop

  --job-metadata arg        Job metadata
  --file-metadata arg       File metadata

  --file-size arg           File size (in Bytes)

  --json-submission         The bulk submission file will be expected in JSON format

  --retry arg               Number of retries. If 0, the server default will be used. If negative, there will be no retries.
  --retry-delay arg (=0)    Retry delay in seconds

  --nostreams arg           Number of streams.
  --timeout arg             Timeout (expressed in seconds)
  --buff-size arg           Buffer size (expressed in bytes)
  --strict-copy             Disable all checks, just copy the file
  --credentials arg         Additional credentials for the transfer (i.e. S3)

.SH SEE ALSO
http://fts3-service.web.cern.ch/
