-- Set of commands to run when a user different than the owner of the schema
-- is used to access the database. Drop commands.
-- SET HEA OFF
-- SET FEED OFF
-- SET NEWP NONE

-------------------
-- DROP SYNONYMS --
-------------------
-- As the schema owner:
-- SELECT 'DROP SYNONYM ' || table_name || ';'  FROM user_tables;
-- SELECT 'DROP SYNONYM ' || sequence_name || ';' FROM user_sequences;
--
-- As the fts3 user:
--
DROP SYNONYM T_SERVER_SANITY;
DROP SYNONYM T_SERVER_CONFIG;
DROP SYNONYM T_OPTIMIZE_MODE;
DROP SYNONYM T_OPTIMIZE;
DROP SYNONYM T_OPTIMIZER_EVOLUTION;
DROP SYNONYM T_CONFIG_AUDIT;
DROP SYNONYM T_DEBUG;
DROP SYNONYM T_CREDENTIAL_CACHE;
DROP SYNONYM T_CREDENTIAL;
DROP SYNONYM T_CREDENTIAL_VERS;
DROP SYNONYM T_SE;
DROP SYNONYM T_SE_ACL;
DROP SYNONYM T_GROUP_MEMBERS;
DROP SYNONYM T_LINK_CONFIG;
DROP SYNONYM T_SHARE_CONFIG;
DROP SYNONYM T_ACTIVITY_SHARE_CONFIG;
DROP SYNONYM T_BAD_SES;
DROP SYNONYM T_BAD_DNS;
DROP SYNONYM T_SE_PAIR_ACL;
DROP SYNONYM T_VO_ACL;
DROP SYNONYM T_JOB;
DROP SYNONYM T_FILE;
DROP SYNONYM T_FILE_RETRY_ERRORS;
DROP SYNONYM T_FILE_SHARE_CONFIG;
DROP SYNONYM T_STAGE_REQ;
DROP SYNONYM T_HOSTS;
DROP SYNONYM T_OPTIMIZE_ACTIVE;
DROP SYNONYM T_OPTIMIZE_STREAMS;
DROP SYNONYM T_SCHEMA_VERS;
DROP SYNONYM T_FILE_BACKUP;
DROP SYNONYM T_JOB_BACKUP;
DROP SYNONYM T_DM_BACKUP;
DROP SYNONYM T_DM;
DROP SYNONYM T_PROFILING_INFO;
DROP SYNONYM T_PROFILING_SNAPSHOT;
DROP SYNONYM T_TURL;
DROP SYNONYM T_CLOUDSTORAGE;
DROP SYNONYM T_CLOUDSTORAGEUSER;

DROP SYNONYM FILE_FILE_ID_SEQ;
DROP SYNONYM SE_ID_INFO_SEQ;
DROP SYNONYM T_OPTIMIZE_AUTO_NUMBER_SEQ;

