FIND_PATH(GLIB2_INCLUDE_DIR glib.h
  PATHS
    /usr/include/glib-2.0
)

FIND_PATH(GLIB2_CFG_INCLUDE_DIR glibconfig.h
  PATHS
    /usr/lib64/glib-2.0/include
)

SET(GLIB2_FOUND 0)
IF(GLIB2_INCLUDE_DIR)
  if(GLIB2_CFG_INCLUDE_DIR)
    SET(GLIB2_FOUND 1)
    MESSAGE(STATUS "Found Glib2")
  ENDIF(GLIB2_CFG_INCLUDE_DIR)
ENDIF(GLIB2_INCLUDE_DIR)

MARK_AS_ADVANCED(
  GLIB2_INCLUDE_DIR
  GLIB2_CFG_INCLUDE_DIR
) 
