INCLUDE(FindPkgConfig)

PKG_SEARCH_MODULE(GLIB2 "REQUIRED" glib-2.0)

IF(GLIB2_FOUND)
  MESSAGE(STATUS "Found Glib2")
ENDIF(GLIB2_FOUND)

MARK_AS_ADVANCED(
  GLIB2_INCLUDE_DIR
  GLIB2_CFG_INCLUDE_DIR
) 
