INCLUDE(FindPkgConfig)

PKG_SEARCH_MODULE(SOUP "REQUIRED" libsoup-2.4 libsoup-2.2)

IF(SOUP_FOUND)
  MESSAGE(STATUS "Found libsoup")
ENDIF(SOUP_FOUND)

MARK_AS_ADVANCED(
  SOUP_CFLAGS
  SOUP_LIBRARIES
) 
