INCLUDE(FindPkgConfig)

PKG_SEARCH_MODULE(SOUP "REQUIRED" libsoup-2.4 libsoup-2.2)

string (REGEX MATCHALL "[0-9]+" _versionComponents "${SOUP_VERSION}")
list(GET _versionComponents 0 SOUP_VERSION_MAJOR)
list(GET _versionComponents 1 SOUP_VERSION_MINOR)

IF(SOUP_FOUND)
  MESSAGE(STATUS "Found libsoup ${SOUP_VERSION_MAJOR}.${SOUP_VERSION_MINOR}")
ENDIF(SOUP_FOUND)

MARK_AS_ADVANCED(
  SOUP_CFLAGS
  SOUP_LDFLAGS
  SOUP_VERSION_MAJOR
  SOUP_VERSION_MINOR
) 
